### ISSUE TITLE
I wanna add folder icon.

### ISSUE THREAD

**Issue by nguyentuandat** [ivogabe/Brackets-Icons#102]
I wanna add folder icon. So how i can do? 
Thanks

**Comment by nguyentuandat** [comment]
I was found out a way:
`main.js`
Change
`
if (!entry.isFile) {
            return;
        }
`
to:
`
if (!entry.isFile) {
            var data = [{color: "#666", icon: "ion-android-folder", size: 15}];
            //return;
        }
`
`style.css`

`
.jstree-brackets li.jstree-closed>a, .jstree-brackets li.jstree-open>a {
    color: #A1CF82;
}
.jstree-open>a, .jstree-closed>a{
    margin-left: 18px;
}
`

That's it

**Comment by ivogabe** [comment]
Directories get the default icon of Brackets (an arrow), that changes when you open a directory. I think that icon is clear enough, and I prefer to keep it that way.

**Comment by nguyentuandat** [comment]
My code above help add folder icon and also keep arrow :)
