### ISSUE TITLE
Default icons doesn't hide

### ISSUE THREAD

**Issue by 50l3r** [ivogabe/Brackets-Icons#104]
I install brackets icons extension but default icons doesn't remove:

![image](https://i.gyazo.com/0677a118f43339333f883c456069889c.png)

**Comment by ivogabe** [comment]
As far as I know, Brackets doesn't have default icons. Do you have some other extension installed that adds icons?

**Comment by 50l3r** [comment]
You were right

Problem caused by other extension:https://github.com/DH3ALEJANDRO/custom-work-for-brackets

Setting this two preferences works fine:

    "custom.work.geticonprovider": false,
    "custom.work.addiconprovider": false,

**Comment by Mujaddadi** [comment]
I am having the same issue. Where do I have to add this preference?
