### ISSUE TITLE
Alignment error with Brackets Working File Tab

### ISSUE THREAD

**Issue by tgottc** [ivogabe/Brackets-Icons#107]
There is a small alignment error with Ionicons. The same does not happen with Devicons.
Extension: https://github.com/demonmhon/brackets-working-file-tabs
<img width="505" alt="screen shot 2016-04-30 at 15 02 03" src="https://cloud.githubusercontent.com/assets/11369395/14937645/9724b2d4-0ee4-11e6-920f-744283443fa6.png">
<img width="508" alt="screen shot 2016-04-30 at 15 02 26" src="https://cloud.githubusercontent.com/assets/11369395/14937646/9a6a359a-0ee4-11e6-838a-4385cc14f53d.png">

**Comment by ivogabe** [comment]
I think that this should be fixed in that extension, since I cannot support every extension that modifies the UI.
