### ISSUE TITLE
It disable and shows "Extension error"

### ISSUE THREAD

**Issue by accjiyun** [ivogabe/Brackets-Icons#111]
I installed your extension, but it disable and shows "Extension error".
How can i solve this problem?
![screenshot from 2016-07-30 20-17-16](https://cloud.githubusercontent.com/assets/13925761/17270348/25650e7c-5693-11e6-9d60-1cb88da2bdf5.png)

**Comment by accjiyun** [comment]
![screenshot from 2016-07-30 20-27-34](https://cloud.githubusercontent.com/assets/13925761/17270391/1e2bbd76-5694-11e6-8d1e-c1f4fb157292.png)

The latest version is also such error.

**Comment by ivogabe** [comment]
Did you install it using the extension manager or directly fro GitHub? The latter doesn't work, you must download a zip file from the releases tab if you want to download it from GitHub.

**Comment by accjiyun** [comment]
Thanks! I successed with use the Brackets's extension manager online install the extension.
