### ISSUE TITLE
extension causes error with brackets

### ISSUE THREAD

**Issue by alvint** [ivogabe/Brackets-Icons#62]
main.js line 213 throws this error:

`GET file:///Applications/Brackets.app/Contents/www/img/glyphicons-halflings.png net::ERR_FILE_NOT_FOUND`

There is no `www/img` folder in brackets. This is just a guess, but maybe it only works with the version of Brackets that bundles Adobe Extract?

The error doesn't appear to be fatal, but it is annoying to a certain type of developer (you know, the type of developer that would use Brackets in the first place).

**Comment by ivogabe** [comment]
Thanks for reporting. It turns out that the stylesheet of Brackets sets the background-image of all elements with a classname that starts with `icon-`. The javascript icon (and c, cpp, cs, hx, perl, swift & typescript) use the classname `icon-c`. I've renamed it to `file-icon-c` to solve the issue.

**Comment by alvint** [comment]
I'm still getting this error with the latest version:

![screen shot 2015-02-18 at 7 03 20 pm](https://cloud.githubusercontent.com/assets/622202/6259457/e6749fc6-b7a0-11e4-9a08-59d5774b775a.png)
