### ISSUE TITLE
Add support of .ctp and .blade.php files.

### ISSUE THREAD

**Issue by Xety** [ivogabe/Brackets-Icons#71]
Hello,

It would be nice to support `.ctp` extension and attribute the php icon. This extension is used in the PHP framework [CakePHP](http://cakephp.org).

Also, it would be nice to support the `.blade.php` extension, and add a new icon for it :
![http://laravel.com/assets/img/laravel-logo.png](http://laravel.com/assets/img/laravel-logo.png)
Or
![http://laravel.com/favicon.png](http://laravel.com/favicon.png)

This extension is used in the PHP Framework [Laravel](http://laravel.com)

**Comment by ivogabe** [comment]
There is already an icon for .php files, so .blade.php has that one already and I prefer to keep it that way. I've added .ctp with the same icon as .php (since it's the same family), but with a different color.

**Comment by Xety** [comment]
Awesome, thanks you !
