### ISSUE TITLE
Similar Package for Sublime Text

### ISSUE THREAD

**Issue by Shakil-Shahadat** [ivogabe/Brackets-Icons#72]
Hi, I really loved your extension. I looked up similar package for Sublime Text with no luck. Is it possible to make a similar package for Sublime Text?

Thanks.

**Comment by ivogabe** [comment]
I forgot this issue for a while, sorry about that. I won't make such a package for Sublime Text, but if someone else would want to create such package I can move the icon list to a different repo so the two extensions can use the same list of icons.
