### ISSUE TITLE
support for config.json

### ISSUE THREAD

**Issue by thoroc** [ivogabe/Brackets-Icons#75]
Hi,

is there a way to get the ```gulpfiles.js```, the ```packages.json``` and the ```bower.json``` to have specific icons? 

thanks

**Comment by ivogabe** [comment]
Currently that's not supported. If you'd want to create a pull request, you should change the code [here](https://github.com/ivogabe/Brackets-Icons/blob/c68cc94ad3d3275b9220cd71acca1975ba489d40/main.js#L244). You should start with the full filename (for example foo.bar.js), check whether such extension exists. If not: remove the first part (till the first dot) and check whether bar.js exists etcetera.

That approach would also allow files as `**.conf.js` to have it's own icon. `gulpfile.js` would have the same icon as `foo.gulpfile.js` with that approach, but that's not a problem for me.

**Comment by ivogabe** [comment]
See #79.

**Comment by thoroc** [comment]
nice :)
