### ISSUE TITLE
Extension name customization

### ISSUE THREAD

**Issue by louiealmeda** [ivogabe/Brackets-Icons#76]
This would be better if we can customize the icons for extension names like: tests.spec.js, in the current version it can only see 'js' and not 'spec.js'

**Comment by ivogabe** [comment]
Thanks for the suggestion, I've been thinking about this too. I hope to start working on this soon.

**Comment by ivogabe** [comment]
See #79. In short, a secondary icon (for the `spec` part) will be added to the right bottom.

**Comment by ivogabe** [comment]
Released in v1.5.0. I've added icons for `.spec.js`, `.test.js` and `.min.js`, but you can of course add your own icons.
