### ISSUE TITLE
Add support for NPM, Gulp and Grunt

### ISSUE THREAD

**Issue by vorillaz** [ivogabe/Brackets-Icons#78]
First things first thanks a lot for using Devicons 

I would love to have my gulp, npm and grunt related files mapped with their icons. Seti_UI theme for Sublime Text has a similar functionality

**Comment by ivogabe** [comment]
Thanks for the suggestion. I've been thinking about rewriting the icons dictionary to support additional features like this one. I hope to start working on it soon.

**Comment by ivogabe** [comment]
See #79

**Comment by ivogabe** [comment]
Released in v1.5. You need to set the icon set to devicons in the view menu.
