### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by jasotastic** [ivogabe/Brackets-Icons#83]
Just tried to install from .zip to Brackets. Installation failed: The extension encountered an error while starting up. The previous version was working. (I was able to reinstall the old version to verify that my Brackets installation was not the issue.)

Windows 8.1 Pro x64
Brackets 1.3.0-16022

**Comment by cgfrost** [comment]
I've seen this on OSX 10.10.4 as well. 
Brackets 1.3 build 1.3.0-16022
It dosn't seem to happen everytime, my desktop upgraded to 1.5 with no problems, my laptop kept hanging while starting up.

**Comment by ivogabe** [comment]
I switched to TypeScript and the project now requires a build step. When you install the extension from the extension manager, you'll get a build version, but the repository here on GitHub doesn't contain the build (javascript) files, only the source (typescript) files. I'm not sure whether there is a good fix for it, as I don't want to commit both javascript as typescript files on GitHub, and I don't think Brackets supports a build step after installing it. You can see in the readme how you can build it, but I would advice you to download the extension from the extension manager in Brackets.

Suggestions for a fix would be welcome.

**Comment by jasotastic** [comment]
It looks like my issue may stem from being in a work environment and bad certificates from several sources including node. A similar issue prevents me from installing directly through brackets. 

Shame about that decision to switch to TypeScript. Previously, I was able to get around the connection/certificate issue by installing the zip downloaded from by dragging it into Brackets. If you change back, I'll reinstall.

**Comment by ivogabe** [comment]
I can release built files as a .zip file on the [releases](https://github.com/ivogabe/Brackets-Icons/releases) page, would that solve your issue?

**Comment by jasotastic** [comment]
I'd be willing to try and let you know how it goes.

**Comment by ivogabe** [comment]
You can download the new release [here](https://github.com/ivogabe/Brackets-Icons/releases/tag/v1.5.1) (click on `Brackets-Icons.zip`). Does that work for you?

**Comment by rifton007** [comment]
Hello,

I also just installed the update.
Since the extension does not.
Is there a log file?

**Comment by rifton007** [comment]
Hello,

I also just installed the update.
Since the extension does not.
Is there a log file?

**Comment by cgfrost** [comment]
@rifton007 The extension doesn't do any logging. Where you expecting anything else?
To see what Brackets is doing you can click `Debug` -> `Show Developer Tools`

**Comment by ivogabe** [comment]
@rifton007 Is this related to #89? How did you install Brackets Icons? (Using the extension manager?)

**Comment by rifton007** [comment]
Thank you,
The problem is set from the update.

**Comment by ivogabe** [comment]
@jasotastic Have you tried downloading a zip from the releases tab? Did it work for you?

**Comment by jasotastic** [comment]
I'm sorry. I just now got to this. It did work when I downloaded the .zip from the releases. Thank you for your work.
