### ISSUE TITLE
Use the Brackets Icon

### ISSUE THREAD

**Issue by Hirse** [ivogabe/Brackets-Icons#85]
I really like the idea of secondary icons and I have one improvement:
Use the [Brackets Icon](http://vorillaz.github.io/devicons/#/singleicon/brackets) for `brackets.json` and `.brackets.json` files.

**Comment by ivogabe** [comment]
Glad you like it! Can you create a pull request?

**Comment by Hirse** [comment]
I started, but I didn't find a good Ionicons icon for it yet.
Is it necessary to have both?

**Comment by ivogabe** [comment]
No, one is also good
