### ISSUE TITLE
Only show secondary icon for know filenames and extensions

### ISSUE THREAD

**Issue by Hirse** [ivogabe/Brackets-Icons#88]
The best way to explain is probably by example:
![capture](https://cloud.githubusercontent.com/assets/2564094/8785877/0b3f722a-2f2b-11e5-9ec5-c7ae5dcf866e.PNG)
Here I have three files with a secondary icon.
The first one - correctly - because of the combination of filename and file extension is somewhat reserved.
The second one - also correctly - because it has a secondary file extension.
The third one - in my opinion incorrectly - because the *svg* is not a secondary file extension but just the name of the file.

**Comment by cgfrost** [comment]
To put it another way, you think the first element (the bit before the first dot) of a file name should be ignored unless it's a known file name such as `package.json`?

**Comment by Hirse** [comment]
Yes, pretty much.
To be more precise, in a filename with many dots only the part after the second last dot should be considered.

**Comment by cgfrost** [comment]
That change would mean a little more. e.g. `foo.js.bar.boo` would currently get the extension for a JS file. If we ignore everything before the second from last dot it will only get the default icon. @ivogabe What do you think? (I'm happy to do the work for this change, I have some spare time tomorrow, I don't want to barge in before you though)

**Comment by ivogabe** [comment]
I think the behavior proposed by @Hirse is the best. `svg.html` is probably not a svg file, only a html file and `foo.js.bar.boo` is probably not a javascript file, so we should give it the default icon. A file like `foo.js.bar` is comparable to `foo.js.php`, it can be for instance a .bar / .php file that generates a .js file, so we should give `foo.js.bar` the default icon as primary icon and .js as secondary.

**Comment by cgfrost** [comment]
@ivogabe  OK, do you mind if I make this change and fix the bug in the other issue at the same time. Will be much quicker because I already started playing with this before the bug was raised?

**Comment by ivogabe** [comment]
@cgfrost That would be great

**Comment by cgfrost** [comment]
This pull request will fix things. (I'll stop tweeking the pull request as well)

**Comment by yvza** [comment]
How about this? http://prnt.sc/eta6rj
@cgfrost
