### ISSUE TITLE
Release 1.5.1 is freezing Brackets

### ISSUE THREAD

**Issue by Pikoulol** [ivogabe/Brackets-Icons#89]
Hi,

Since I've updated Brackets-Icons from 1.5.0 to 1.5.1. My brackets UI is not responding.
When I open Brackets, the main window and the files tree is empty.
The top menu is visible but not responding.

To get it working again I've to move Brackets-Icons to the disabled extensions folder then restart Brackets.

Plugins installed :
- Brackets Outline List
- Documents Toolbar
- Extensions Rating
- Todo
- Tomorrow Night

**Comment by Pikoulol** [comment]
I made a test with Brackets and only your plugin installed. 
Problem stays the same. So, it's not a conflict between plugins.

**Comment by cgfrost** [comment]
I think I know what might be causing this, I'll see if I can fix it. I can recreate the problem you are describing at least.

**Comment by ivogabe** [comment]
It looks to be only failing on Windows, on a Mac it runs without trouble.

@cgfrost What cause do you suspect? Can you create a fix?

**Comment by cgfrost** [comment]
I think it's the main loop in `findInDictionary`, I think there are some strange cases where it will never exit and keep looping. I'm working on it now. Should have a fix in the next hour or so.

**Comment by Hirse** [comment]
The problem occurs when the extension is deciding on the icon for a file whose name is not in the list of known file names and consists only of the file extension.

**Comment by Hirse** [comment]
This is fine:
![2015-07-21 11-27-53](https://cloud.githubusercontent.com/assets/2564094/8797444/b0eabbd8-2f9b-11e5-8b0b-a60047e8622f.png)
But when I create a new file with a name like this it freezes as soon as I press enter.
![2015-07-21 11-28-35](https://cloud.githubusercontent.com/assets/2564094/8797456/c1696c02-2f9b-11e5-9d20-f6d6c429c6a7.png)

**Comment by ivogabe** [comment]
@cgfrost The bug is probably on line 70, when dotIndex is 0 (as in the example of @Hirse), it'll pass -1 as the second argument to lastIndexOf, which probably means the second argument is ignored. dotIndexNext is then again 0, and that introduces an infinite loop. It should be assigned -1 instead.

**Comment by cgfrost** [comment]
Yeah, that is close to how I have recreated it. (I'm on a Mac by the way so I don't think this is Windows specific)

**Comment by cgfrost** [comment]
This pull request will fix things. (I'll stop tweeking the pull request as well)

**Comment by ivogabe** [comment]
Fixed in 1.5.2. The issue was indeed also available on Mac. (I didn't open any directories containing these unknown dot files on Mac, but I did open these on Windows)

**Comment by ivogabe** [comment]
If you have issues updating to 1.5.2, because Brackets doesn't respond any more due to the infinite loop, you should first remove Brackets Icons (`ivogabe.icons`) from the extensions directory:
- Mac: `~/Library/Application Support/Brackets/extensions/user`
- Win: `C:\Users\<user>\AppData\Roaming\Brackets\extensions\user`
- Linux: `~/.config/brackets/extensions/user`

**Comment by Pikoulol** [comment]
I've updated the plugin to version 1.5.2 and everything works fine now. 

Thank you guys !
