### ISSUE TITLE
Not able to view icons on my files

### ISSUE THREAD

**Issue by vivekdhiman** [ivogabe/Brackets-Icons#96]
Hi,
I have installed the extension, but not able to view my icons on the files. Any settings i am missing?
![test](https://cloud.githubusercontent.com/assets/7066652/9523987/28cf97c4-4cfa-11e5-98d1-fd5065726dac.png)

**Comment by ivogabe** [comment]
Hard to say what's going on.. Can you see Brackets Icons in the installed extensions tab of the extension manager? Is there anything related to Icons in the console ([Debug > Show Developer Tools](https://github.com/adobe/brackets/wiki/Debugging-Brackets))?

**Comment by vivekdhiman** [comment]
This is the error i am getting on developer console:
[Extension] failed to load /home/vivekd/.config/Brackets/extensions/user/ivogabe.icons - Module does not exist: file:///home/vivekd/.config/Brackets/extensions/user/ivogabe.icons/dist/main.js

**Comment by ivogabe** [comment]
Looks like you downloaded the sources from GitHub. These are not compiled, you can [build](https://github.com/ivogabe/Brackets-Icons#how-to-build) them yourself or use a prebuilt download from the [releases page](https://github.com/ivogabe/Brackets-Icons/releases) or from the extension manager in Brackets. I'd advice to use the latter, that will make updating very easy. Does this solve your question?

**Comment by ivogabe** [comment]
@vivekdhiman Any updates? Is this solved for you?

**Comment by vivekdhiman** [comment]
Yehh, Solved. Installed new version of Brackets without any existing plugin & then installed brackets-icons. Its really cool.
